name: Build Custom Photon Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore NuGet packages
      run: dotnet restore RepoCustomPhotonServer.sln

    - name: Build solution
      run: dotnet build RepoCustomPhotonServer.sln --configuration Release

    - name: Copy core DLLs
      run: |
        mkdir output
        copy core\* output\

    - name: Copy project output
      run: copy RepoCustomPhotonServer\bin\Release\netstandard2.1\* output\

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: CustomPhotonServer
        path: output/
